@startuml
class Datos
class EulerMejorado
class Menu 
class Metodo 
class Validacion 
//
EulerMejorado -* Menu
EulerMejorado -o Metodo
EulerMejorado -|> Metodo
Menu -o Datos
Validacion -o Datos
@enduml